---
- hosts: "{{ target | default('nomad-masters') }}"
  any_errors_fatal: true
  become: yes

  vars_files:
    - "{{ playbook_dir }}/../envvars.yml"

  tasks:
    - name: push nomad jobs folder
      file:
        path: "/root/nomad/jobs"
        state: directory
        force: yes

    - name: push nomad job
      template:
        src: "{{ playbook_dir }}/../nomad/jobs/bootstrap-nomad.hcl.j2"
        dest: "/root/nomad/jobs/bootstrap-nomad.hcl"
