---
- hosts: "{{ target|default('all') }}"
  become: yes
  gather_facts: no

  tasks:
    - apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - htop
        - ncdu
        - vim
        - curl
        - git
