---
- name: restart consul
  systemd:
    name: "{{ consul_user_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  tags: update-conf

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
  tags: update-conf
